# deployment da aplicacao backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: byte-burguer-orders-pod
  labels:
    app: byte-burguer-orders-pod
spec:
  template:
    metadata:
      name: orders-byte-burguer-pod
      labels:
        app: orders-byte-burguer-pod
    spec:
      containers:
        - name: byteburguer-api
          image: hiltonbruno633/bytebiteburgersorders-application-service:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: my-secret
          livenessProbe:
            httpGet:
                path: /health_check
                port: 8000
            periodSeconds: 10  
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health_check 
              port: 8000
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              cpu: 10m
            limits:
              cpu: 500m
  replicas: 3
  selector:
    matchLabels: 
      app: orders-byte-burguer-pod
