# deployment da aplicacao backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-byte-burguer-pod
  labels:
    app: orders-byte-burguer-pod
spec:
  template:
    metadata:
      name: orders-byte-burguer-pod
      labels:
        app: orders-byte-burguer-pod
    spec:
      containers:
        - name: byteburguer-order-api
          image: hiltonbruno633/bytebiteburgersorders-application-service:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: orders-secret
  replicas: 1
  selector:
    matchLabels: 
      app: orders-byte-burguer-pod
