apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
type: Opaque
data:
  DATABASE_USERNAME: cG9zdGdyZXM=
  DATABASE_HOST: cmRzLW9yZGVyLmNsNm0wdWttNmF4ZC51cy13ZXN0LTIucmRzLmFtYXpvbmF3cy5jb20=
  DATABASE_PORT: NTQzMg==
  DATABASE_NAME: cG9zdGdyZXM=
  DATABASE_PASSWORD: eTQ1WTpTYVNidnBmRGQuRUUjXzNpZFhaeE4lbQ==
  API_PAGAMENTO_HOST: aHR0cDovL2E2ZGI2ZDc2MWIwOTA0ZWM0OTZlZWEwM2IwYThiMWJjLTkzOTE1MTE2Ny51cy13ZXN0LTIuZWxiLmFtYXpvbmF3cy5jb206ODAwMQ==
  API_USUARIO_HOST: aHR0cDovL2E4MjMzODdkMmU3YjQ0MDY5OGVjZTY2MjkyZDYwYWM0LTYxMzg3MDM0LnVzLXdlc3QtMi5lbGIuYW1hem9uYXdzLmNvbTo4MDAy
  APPLICATION_NAME: YmJiLW9yZGVy
  APPLICATION_HOST: MC4wLjAuMA==
  APPLICATION_PORT: MzAwMA==
  ENVIRONMENT: cHJk
  WORKERS: MQ==
  TIMEOUT_GRACEFUL_SHUTDOWN: MQ==
  QUEUE_URL: aHR0cHM6Ly9zcXMudXMtd2VzdC0yLmFtYXpvbmF3cy5jb20vODIyODUzNjk3NzQzL3NoLWJ5dGVidXJndWVyLXF1ZXVl

  