apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
type: Opaque
data:
  DATABASE_USERNAME: cG9zdGdyZXM=
  DATABASE_HOST: cmRzLW9yZGVyLmNsNm0wdWttNmF4ZC51cy13ZXN0LTIucmRzLmFtYXpvbmF3cy5jb20=
  DATABASE_PORT: NTQzMg==
  DATABASE_NAME: cG9zdGdyZXM=
  DATABASE_PASSWORD: YTI/MTpIMzw5SFlvck5rXS5QKGp0eUstMiNIeg==
  APPLICATION_NAME: YmJiLW9yZGVy
  APPLICATION_HOST: MC4wLjAuMA==
  APPLICATION_PORT: MzAwMA==
  ENVIRONMENT: ZGV2
  WORKERS: MQ==
  TIMEOUT_GRACEFUL_SHUTDOWN: MQ==